### ISSUE TITLE
Bug when using third party rabbitmq package

### ISSUE THREAD

**Issue by syamsf** [bilfeldt/laravel-correlation-id#8]
### No connector for [rabbitmq].

When I attempt to install this library, Composer immediately throws the error "No connector for [rabbitmq]." The same error occurs when I try to start php artisan serve. The configuration in queue.php is already set up as well.

### Environment
- Laravel 11.14
- PHP 8.2
- RabbitMQ package ("vladimir-yuldashev/laravel-queue-rabbitmq": "^14.1")
- queue.php config
```
 'rabbitmq' => [
            'driver' => 'rabbitmq',
            'worker' => env('RABBITMQ_WORKER', 'horizon'),
            'hosts' => [
                [
                    'host'     => env('RABBITMQ_HOST', '127.0.0.1'),
                    'port'     => env('RABBITMQ_PORT', 5672),
                    'user'     => env('RABBITMQ_USER', 'guest'),
                    'password' => env('RABBITMQ_PASSWORD', 'guest'),
                    'vhost'    => env('RABBITMQ_VHOST', '/'),
                ],
            ],
            'retry_after' => 120,
   ],
   ```

### Steps to reproduce

Tell us how to reproduce this issue in steps:

1. I'm using those environment with this rabbitmq package `"vladimir-yuldashev/laravel-queue-rabbitmq": "^14.1"`
2. Install correlation id package `composer require bilfeldt/laravel-correlation-id`
3. It will throw an error

### Expected behaviour
- Error should not be happened

### Actual behaviour
- Error message `No connector for [rabbitmq].`

**Comment by bilfeldt** [comment]
This seems to be an issue related to your queue. I don't think this package is the root cause, but because this package accesses the Queue facade, then your configuration issues might surface when you install this package.

Instead of installing this package, try running the following code:

```php
\Queue::connection();
```

Do you get an error there? If not, try adding the following in the `boot` method of your `AppServiceProvider`

```php
Queue::before(function (JobProcessing $event) {
    // intentionally doing nothing here except interacting with your queue facade
});
```

**Comment by syamsf** [comment]
I've added that code without any issues. When I disable these lines, there is no error saying `No connector for [rabbitmq]`. I haven't investigated further yet, but I believe the code needs more detailed examination.

```
        Queue::createPayloadUsing(function ($connection, $queue, $payload) {
            if (! isset($payload['data'][self::PAYLOAD_KEY_CORRELATION_ID])) {
                $payload['data'][self::PAYLOAD_KEY_CORRELATION_ID] = request()->getCorrelationId();
            }

            return $payload;
        });
```

**Comment by syamsf** [comment]
I believe the issue is due to the order in which external service providers are loaded in `bootstrap/cache/services.php`. The `bilfeldt/laravel-correlation-id` gets loaded before the `vladimir-yuldashev/laravel-queue-rabbitmq`. The problem was resolved when I added it to `dont-discover` and loaded it manually through `providers.php`.

```
"extra": {
        "laravel": {
            "dont-discover": [
                "bilfeldt/laravel-correlation-id"
            ]
        }
    },
```

**Comment by bilfeldt** [comment]
I don't know of a way to control the order of loading, but what you can do is opt out of autoloading of both this packages service provider and `vladimir-yuldashev/laravel-queue-rabbitmq` and then you can manually register the two providers in the order that you want (`vladimir-yuldashev/laravel-queue-rabbitmq` first).
